### ISSUE TITLE
HTTP error

### ISSUE THREAD

**Issue by SaintNoodles** [stanriders/mutualify#4]
![image](https://user-images.githubusercontent.com/108394306/176385058-5b4ffed7-214e-4708-8ea9-083e6be42644.png)

**Comment by stanriders** [comment]
Which page does this happen on?

**Comment by SaintNoodles** [comment]
> Which page does this happen on?

https://mutualify.stanr.info/api/OAuth/complete

**Comment by stanriders** [comment]
I assume you're restricted? Restricted users are not allowed to log in

**Comment by stanriders** [comment]
Fixed via b0a012ecc2d6a4f29178462637b9ae4715f6a738

**Comment by SaintNoodles** [comment]
> I assume you're restricted? Restricted users are not allowed to log in

Oh yeah forgot about that,  thanks for fixing it btw.
