### ISSUE TITLE
Any possibility to add localizations for mutualify?

### ISSUE THREAD

**Issue by lizhanyiawa** [stanriders/mutualify#7]
Although this is not really important,but I think it is a good thing to make a crowdin project or something to add localizations like translations to mutualify to make the user interface more friendly.
If so,I think I can provide translation to Simplified Chinese or so.
Is that okay?

**Comment by stanriders** [comment]
I considered adding localizations to the website before, but then thought there's basically almost no text anyway and whatever is there shouldn't be hard to understand, although I guess for people with pretty much zero english knowledge it might be useful anyway. I'll look into it some time later, if it's not too complicated to implement then sure why not

**Comment by stanriders** [comment]
fdca84e14e92d136aa39a349c64d1c67b0031ea5

https://crowdin.com/project/mutualify should be good to go
